import { Zap, Shield, Settings, Cpu } from 'lucide-react';
import ProductPageTemplate from './ProductPageTemplate';

const pageData = {
  title: 'Automatic Metal Cutting Bandsaw Machine',
  titleLine1: 'AUTOMATIC METAL',
  titleLine2: 'CUTTING BANDSAW',
  intro: 'Leading manufacturer of Automatic Double Column Band Saw Machines. Precisely developed with higher accuracy, unmatched quality components & advanced innovative techniques — built on Pre-hardened LM guideways with touch screen HMI for programmable cutting.',
  badges: [
    { icon: Cpu, label: 'Touch Screen HMI' },
    { icon: Shield, label: 'LM Guide Technology' },
    { icon: Settings, label: 'PLC + Servo Controlled' },
    { icon: Zap, label: 'Fully Automatic' },
  ],
  models: [
    {
      name: '210 LMGA', badge: 'ECONOMY', badgeCls: 'bg-amber-500 text-black',
      subtitle: 'Automatic Metal Cutting Band Saw Machine',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/210_LMGA_Automatic_Double_Column_Bandsaw_Machine_-_Product1-1024x796.jpg',
      desc: '210 LMGA – Automatic Double Column Band Saw Machine Economy series on Pre-hardened LM guideway for smooth operation and high accuracy, specially designed for providing high productivity.',
      features: [
        'Saw frame movement on pre-hardened and pre-loaded LM guides for friction free movement',
        'High Efficiency Power Transmission through helical gear box',
        'Adjustable Dovetail type Heavy duty Movable Blade guide with ball bearing',
        'Automatic switch-off of the blade after finishing the cut',
        'Automatic height stop for saw frame to save idle time',
        'Hydraulic Power Pack with easy maintenance',
        'Double Acting Hydraulic Cylinder for Main vice Clamping & De-clamping',
        'Infinitely variable Feed Control Valve for cutting feed',
        'Electrical control panel with high quality switchgears',
        'PLC controlled electrical control operation',
        'Optional Bundle Clamping Arrangement',
        'Optional Numeric control high accuracy indexing',
      ],
      specs: [
        ['Cutting Capacity', 'Round – 210 mm, Rectangle – 210 × 210 mm'],
        ['Cutting Speed', '20 – 90 mtr/min'],
        ['Blade Size', '4000 × 34 × 1.1 mm'],
        ['Blade Tension', 'Hydraulic'],
        ['Saw Motor', '3.0 HP'],
        ['Hydraulic Motor', '1.5 HP'],
        ['Coolant Motor', '0.12 HP'],
        ['Job Clamping', 'Hydraulic'],
        ['Hydraulic Reservoir', '60 Ltr'],
        ['Overall Dimension', '1900 × 2100 × 1800 mm'],
      ],
    },
    {
      name: '260 LMGA', badge: 'TOUCH SCREEN', badgeCls: 'bg-blue-900 text-white',
      subtitle: '260 Automatic Band Saw Machine with HMI',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/260-automatic-band-saw-machine-2021022958-xtfl3hl0.webp',
      desc: '260 LMGA – Automatic Double Column BandSaw Machine built on Pre-hardened LM guideway. Cutting operations can be programmed through touch screen. HMI offers digital cutting length settings and real-time information such as cutting speed, rate, and pieces count.',
      features: [
        'Saw frame movement on pre-hardened and pre-loaded LM guides for friction free movement',
        'High Efficiency Power Transmission through helical gear box',
        'Hydraulic Blade Tensioning arrangement',
        'Automatic machine off in case of blade breakage or loss of hydraulic pressure',
        'Adjustable Dovetail type Heavy duty Movable Blade guide with ball bearing',
        'Automatic switch-off of the band after finishing the cut',
        'Automatic height stop for saw frame to save idle time',
        'Hydraulic Power Pack with easy operations & maintenance',
        'Double Acting Hydraulic Cylinder for Main vice Clamping & De-clamping',
        'Infinitely variable Feed Control Valve for cutting feed',
        'Electrical control panel with high quality switchgears',
      ],
      specs: [
        ['Cutting Capacity', 'Round – 260 mm, Rectangle – 260 × 260 mm'],
        ['Cutting Speed', '20 – 90 mtr/min'],
        ['Blade Size', '4100 × 34 × 1.1 mm'],
        ['Blade Tension', 'Hydraulic'],
        ['Saw Motor', '5.0 HP'],
        ['Hydraulic Motor', '1.5 HP'],
        ['Coolant Motor', '0.12 HP'],
        ['Job Clamping', 'Hydraulic'],
        ['Job Indexing', '600 mm'],
        ['Hydraulic Reservoir', '60 Ltr'],
        ['Overall Dimension', '2300 × 900 × 2200 mm'],
      ],
    },
    {
      name: '300 LMGA', badge: 'DOUBLE COLUMN', badgeCls: 'bg-orange-700 text-white',
      subtitle: '300 mm Automatic Metal Cutting Band Saw Machine',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/WhatsApp-Image-2024-08-11-at-5.49.16-PM-1024x1024.jpeg',
      desc: '300 LMGA – Automatic Double Column BandSaw Machine on Pre-hardened LM guideway. Machine arm movement based on double column structural rigid platform — stick-slip free movement with smooth and vibration-free cutting.',
      features: [
        'Cutting head movement on pre-hardened LM guides',
        'High Efficiency Power Transmission through helical gear box',
        'Automatic switch-off of the band after finishing the cut',
        'Automatic height stop for saw frame to save idle time',
        'Hydraulic Power Pack with easy operations & maintenance',
        'Hydraulic Blade Tensioning arrangement',
        'Automatic machine off in case of blade breakage or loss of hydraulic pressure',
        'Adjustable Dovetail type Heavy duty Movable Blade guide with ball bearing',
        'Double Acting Hydraulic Cylinder for Main vice Clamping & De-clamping',
        'Infinitely variable Feed Control Valve for cutting feed',
        'Electrical control panel with high quality switchgears',
      ],
      specs: [
        ['Cutting Capacity', 'Round – 300 mm, Rectangle – 300 × 300 mm'],
        ['Cutting Speed', '20 – 90 mtr/min'],
        ['Blade Size', '4400 × 34 × 1.1 mm'],
        ['Blade Tension', 'Hydraulic'],
        ['Saw Motor', '5.0 HP'],
        ['Hydraulic Motor', '2.0 HP'],
        ['Coolant Motor', '0.12 HP'],
        ['Job Clamping', 'Hydraulic'],
        ['Job Indexing', '600 mm'],
        ['Hydraulic Reservoir', '60 Ltr'],
        ['Overall Dimension', '2300 × 900 × 2200 mm'],
      ],
    },
    {
      name: '460 LMGA', badge: 'HEAVY DUTY', badgeCls: 'bg-red-800 text-white',
      subtitle: 'Metal Cutting Automatic Bandsaw Machine',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/460_LMGA_Automatic_Double_Column_Bandsaw_Machine_-_Product1-1-1024x796.jpg',
      desc: '460 LMGA – Metal Cutting Automatic Double Column BandSaw Machine on Pre-hardened LM guideway. Touch Screen HMI interface offers digital cutting length settings and real-time information — cutting speed, rate, pieces count and more.',
      features: [
        'Pre-loaded LM guides for friction free movement of cutting arm',
        'High Efficiency Power Transmission through helical gear box',
        'Hydraulic Blade Tensioning arrangement',
        'Hydraulic material indexing of 500 mm in single stroke',
        'Automatic machine off in case of blade breakage or loss of hydraulic pressure',
        'Adjustable Dovetail type Heavy duty Movable Blade guide with ball bearing',
        'Automatic switch-off of the band after finishing the cut',
        'Automatic height stop for saw frame to save idle time',
        'Hydraulic Power Pack with easy operations & maintenance',
        'Double Acting Hydraulic Cylinder for Main vice Clamping & De-clamping',
        'Touch Screen HMI — digital cutting length settings & real-time data',
      ],
      specs: [
        ['Cutting Capacity', 'Round – 460 mm, Rectangle – 460 × 460 mm'],
        ['Cutting Speed', '20 – 90 mtr/min'],
        ['Blade Tension', 'Hydraulic'],
        ['Saw Motor', '10.0 HP'],
        ['Hydraulic Motor', '3.0 HP'],
        ['Job Clamping', 'Hydraulic'],
        ['Job Indexing', '500 mm/stroke'],
        ['Control System', 'PLC + Touch Screen HMI'],
      ],
    },
  ],
};

export default function AutoBandsawPage({ navigate }) {
  return <ProductPageTemplate pageData={pageData} navigate={navigate} />;
}
