import { Zap, Shield, Settings, Cpu } from 'lucide-react';
import ProductPageTemplate from './ProductPageTemplate';

const pageData = {
  title: 'High Speed Circular Saw Machine',
  titleLine1: 'HIGH SPEED',
  titleLine2: 'CIRCULAR SAW',
  titleLine3: 'MACHINES',
  intro: 'Circular Saw Machines available in numerically controlled, fully automatic, semi-automatic & special purpose versions. Extremely fast compared to conventional bandsaw machines — designed for ferrous and non-ferrous metals including Mild Steel, Alloy Steels, Copper, Bronze, and Aluminium.',
  badges: [
    { icon: Zap, label: 'High Speed Cutting' },
    { icon: Cpu, label: 'Servo + PLC Controlled' },
    { icon: Shield, label: 'TCT / HSS Blades' },
    { icon: Settings, label: 'Auto + Semi-Auto' },
  ],
  models: [
    {
      name: 'FANC-100 (With Auto Loader)', badge: 'NC CONTROLLED', badgeCls: 'bg-amber-500 text-black',
      subtitle: 'Circular Saw Machine with Auto Loader — 25–100mm',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/Untitled-design-4-e1727275985222.png',
      desc: 'Circular Saw Machine with auto loader — numerically controlled, fully automatic version. Provides vibration-free cutting that optimizes production and blade life. Easy operation, long-lasting life, and high authenticity are unique features.',
      features: [
        'Torsion free construction of Heavy duty Fabricated Structure',
        'Infinitely variable servo controlled cutting feed',
        'Cutting feed through Ball Screw Servo motor and VFD for variable cutting speed',
        'Rapid approach movement of Cutting Head by Ball Screw Servo motor',
        'Indexing of material through Ball Screw Servo motor arrangement',
        'Auto rapid return of cutting head after completion of cut',
        'Auto and manual mode for cycle sequence',
        'Hydraulic Operated job clamping horizontal Vice',
        'Heavy duty reduction Gearbox for heavy cutting torque on linear guide ways',
        'Micro mist spray cooling arrangement',
        'Motorized wire brush for cleaning chips from circular blade',
        'Automatic trim cut with enable/disable option',
        'PLC Control system with 7" Touch Screen HMI',
        'Automatic Lubrication pump',
      ],
      specs: [
        ['Cutting Capacity', '25 – 100 mm (Round)'],
        ['Cutter Type', 'TCT / HSS'],
        ['Cutter Size', '360 & 420 × 2.5 mm'],
        ['Saw Motor', '20.0 HP'],
        ['Hydraulic Motor', '2.0 HP'],
        ['Coolant Motor', '0.15 HP'],
        ['Job Clamping', 'Hydraulic'],
        ['Hydraulic Reservoir', '90 Ltr'],
        ['Electrical Control', 'Through PLC Panel'],
      ],
    },
    {
      name: '70 FANC', badge: 'SEMI-AUTO', badgeCls: 'bg-blue-900 text-white',
      subtitle: 'Circular Sawing Machine — 25–70mm',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/09/85-CSM--e1727276468452-1024x890.jpg',
      desc: 'Circular sawing machines for cutting up bars and tubes in diverse industries. Specially designed for high rate of production and more accuracy each time. Available in semi-automatic and fully automatic versions with heavy duty construction.',
      features: [
        'Torsion free construction of Heavy duty Fabricated Structure',
        'Infinitely variable controlled cutting feed',
        'Cutting feed through Ball Screw Servo motor and VFD',
        'Rapid approach movement of Cutting Head by Ball Screw Servo motor',
        'Indexing of job through Ball Screw Servo motor arrangement',
        'Hydraulic Operated job clamping horizontal Vice',
        'Heavy duty reduction Gearbox — vibration free cutting',
        'Inbuilt flood coolant tank and micro mist cooling arrangement',
        'Separate Hydraulic Power pack for easy check & maintenance',
        'Driver brushes for cleaning chips from circular blades',
        'Automatic trim cut option',
        'Crop Cut & End Cut Separator',
        'PLC Control system with Touch Screen HMI',
        'Auto Lubrication pump',
      ],
      specs: [
        ['Cutting Capacity', '25 – 70 mm (Round)'],
        ['Cutter Type', 'TCT / HSS'],
        ['Cutter Size', '285 & 315 × 2.0 mm'],
        ['Saw Motor', '12.5 HP'],
        ['Hydraulic Motor', '2.0 HP'],
        ['Coolant Motor', '0.15 HP'],
        ['Job Clamping', 'Hydraulic'],
        ['Hydraulic Reservoir', '90 Ltr'],
        ['Electrical Control', 'Through PLC Panel'],
      ],
    },
    {
      name: '80 FANC', badge: 'FULLY AUTO', badgeCls: 'bg-red-800 text-white',
      subtitle: 'Fully Automatic Circular Saw Machine — 15–80mm',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/fully-automatic-circular-saw-machine-80-fanc-2021023335-30dtkrm8.jpg',
      desc: 'Fully Automatic Circular Saw Machine — high productive, accurate and compact. High rate of production at comparatively low investment. Provides vibration-free cutting that optimizes production and blade life.',
      features: [
        'Torsion free construction of Heavy duty Fabricated Structure',
        'Infinitely variable controlled cutting feed',
        'Cutting feed through Ball Screw Servo motor and VFD',
        'Rapid approach movement of Cutting Head by Ball Screw Servo motor',
        'Saw motor speed controlled with A.C. frequency drive',
        'Horizontal Saw stroke, optimized to achieve shortest stroke',
        'Driver brushes for cleaning chips from circular blades',
        'Indexing of job through Ball Screw Servo motor arrangement',
        'Auto return of cutting head after completion of cut',
        'Auto and manual mode for cycle sequence',
        'Heavy duty reduction Gearbox directly coupled to main saw motor on linear guide ways',
        'Inbuilt flood coolant tank and micro mist cooling arrangement',
        'Automatic trim cut',
        'Crop Cut & End Cut Separator',
        'PLC Control system with Touch Screen HMI',
        'Auto Lubrication pump',
      ],
      specs: [
        ['Cutting Capacity', '15 – 80 mm (Round)'],
        ['Cutter Type', 'TCT / HSS'],
        ['Cutter Size', '285 & 315 × 2 mm'],
        ['Saw Motor', '12.5 HP'],
        ['Hydraulic Motor', '2.0 HP'],
        ['Coolant Motor', '0.15 HP'],
        ['Job Clamping', 'Hydraulic'],
        ['Hydraulic Reservoir', '80 Ltr'],
        ['Electrical Control', 'Through PLC Panel'],
      ],
    },
  ],
};

export default function CircularSawPage({ navigate }) {
  return <ProductPageTemplate pageData={pageData} navigate={navigate} />;
}
