import { Zap, Shield, Settings } from 'lucide-react';
import ProductPageTemplate from './ProductPageTemplate';

const pageData = {
  title: 'Swing Type Bandsaw Machine',
  titleLine1: 'SWING TYPE',
  titleLine2: 'BANDSAW MACHINES',
  titleLine3: '',
  intro: 'MEC Technology manufactures swing type straight cutting as well as angular cutting semi-automatic hydraulic bandsaw machines. Dimensional accuracy, easy installation, plug and play option, high cutting speed, and robustness are key features.',
  badges: [
    { icon: Zap, label: '4 Models Available' },
    { icon: Shield, label: 'Hydraulic Clamping' },
    { icon: Settings, label: 'PLC Controlled' },
  ],
  models: [
    {
      name: 'MEC 200 SCH', badge: 'SEMI-AUTO', badgeCls: 'bg-amber-500 text-black',
      subtitle: 'Swing Type Semi Automatic Hydraulic Bandsaw Machine',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/swing-type-bandsaw-machine-200-sch-2021022446-z4rfdono.avif',
      desc: 'MEC – 200 SCH is swing type semi-automatic hydraulic bandsaw machine made for metal industry professionals. Solid, robust, stable, compact and highly accurate metal cutting solution with angular cutting option.',
      features: [
        'Hydraulic job clamping',
        'Hydraulic cylinder feed control',
        'Auto Saw Off after finishing cut',
        'Auto Head Up after finishing cut',
        'Machine with easy control & working height 700 mm',
        'Hydraulic Power Pack with easy maintenance',
        'Double Acting Hydraulic Cylinder for Main vice Clamping & De-clamping',
        'Infinitely variable Feed Control Valve for cutting feed & upward movement',
        'Electrical control panel with high quality switchgears',
        'PLC controlled electrical control operation',
        'Optional Bundle Clamping Arrangement',
        'Optional Numeric control high accuracy indexing',
      ],
      specs: [
        ['Cutting Capacity', 'Round – 200 mm, Rectangle – 200 × 200 mm'],
        ['Cutting Speed', '20 – 60 mtr/min'],
        ['Blade Size', '2910 × 27 × 0.9 mm'],
        ['Blade Tension', 'Manual'],
        ['Saw Motor', '2.0 HP'],
        ['Hydraulic Motor', '0.5 HP'],
        ['Coolant Motor', '0.12 HP'],
        ['Job Clamping', 'Hydraulic'],
        ['Job Indexing', 'Manual'],
        ['Hydraulic Reservoir', '25 Ltr'],
        ['Overall Dimension', '1360 × 600 × 1100 mm'],
      ],
    },
    {
      name: 'MEC 200 SCM (8")', badge: 'MANUAL', badgeCls: 'bg-steel-700 text-white',
      subtitle: 'Manual Bandsaw Machine — Small Units',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/manual-bandsaw-machine-8-2021022415-ipab4mgd.avif',
      desc: '200 SCM is swing type manually operated bandsaw machine made for small units of metal industry. Solid, robust, stable, compact and highly accurate. Cuts tubes, rods, shafts, round, rectangle, square materials — mild steel, stainless steel, non-ferrous metals.',
      featuresLabel: 'Main Features',
      features: [
        'Manual bandsaw machine',
        'Auto Saw Off after finishing cut',
        'Machine with easy control & working height 420 mm',
        'Complete with Electricals — saw drive motor, coolant pump, on/off contactor with push buttons',
        'V-belt pulleys with V-belt',
        'Friction Type Chip Removal Wire Brush',
      ],
      optionalLabel: 'Optional Accessories',
      optional: [
        'Chip Removal Wire Brush',
        'Bi-metal Bandsaw Blades',
        'Carbon Steel Bandsaw Blades',
        'Job Roller Stand',
        'Mechanical Job Feeder Unit',
      ],
      specs: [
        ['Cutting Capacity', 'Round – 200 mm, Rectangle – 200 × 175 mm'],
        ['Cutting Speed', '20 – 60 mtr/min'],
        ['Blade Size', '3000 × 27 × 0.9 mm'],
        ['Blade Tension', 'Manual'],
        ['Saw Motor', '1.0 HP'],
        ['Coolant Motor', '0.1 HP'],
        ['Job Clamping', 'Manual'],
        ['Coolant Reservoir', '20 Ltr'],
        ['Overall Dimension', '1360 × 600 × 1100 mm'],
      ],
    },
    {
      name: 'MEC 200 SCH (Std)', badge: 'STANDARD', badgeCls: 'bg-blue-900 text-white',
      subtitle: 'Swing Type Bandsaw Machine — 200 SCH Standard',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/swing-type-semi-automatic-bandsaw-machine-2021022385-03n0h3ss.avif',
      desc: 'MEC – 200 SCH is swing type semi-automatic hydraulic bandsaw machine with standard features for metal industry professionals. Solid, robust, stable, compact and highly accurate metal cutting solution.',
      featuresLabel: 'Standard Features',
      features: [
        'Hydraulic cylinder feed control',
        'Auto Saw Off after finishing cut',
        'Machine with easy control & working height 700 mm',
        'Double Acting Hydraulic Cylinder for Main vice Clamping & De-clamping',
        'Infinitely variable Feed Control Valve for cutting feed & upward movement',
        'Electrical control panel with high quality switchgears',
        'Optional Bundle Clamping Arrangement',
      ],
      specs: [
        ['Cutting Capacity', 'Round – 200 mm, Rectangle – 200 × 190 mm'],
        ['Cutting Speed', '20 – 80 mtr/min'],
        ['Blade Size', '2910 × 27 × 0.9 mm'],
        ['Blade Tension', 'Manual'],
        ['Saw Motor', '2.0 HP'],
        ['Coolant Motor', '0.12 HP'],
        ['Job Clamping', 'Manual'],
        ['Job Indexing', 'Manual'],
        ['Overall Dimension', '1360 × 700 × 1100 mm'],
      ],
    },
    {
      name: 'MEC 200 ACH', badge: 'ANGULAR', badgeCls: 'bg-orange-700 text-white',
      subtitle: 'Degree Cutting / Miter Bandsaw Machine',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/kl-1024x796.jpg',
      desc: 'MEC – 200 ACH is swing type angular cutting semi-automatic hydraulic bandsaw machine. Its angular cutting head option provides a wide range of metal cutting solution with high accuracy — 45° to 60° cutting capability.',
      featuresLabel: 'Main Features',
      features: [
        'Semi Automatic bandsaw machine',
        'Rotary cutting arm for wide range of angular cutting',
        '45–60 degree cutting can be performed',
        'Hydraulic job clamping',
        'Hydraulic cylinder feed control',
        'Auto Saw Off after finishing cut',
        'Auto Head Up after finishing cut',
        'Machine with easy operation',
      ],
      specs: [
        ['Cutting Capacity (90°)', 'Round – 200 mm, Rectangle – 200 × 180 mm'],
        ['Cutting Capacity (45°)', 'Round – 130 mm, Rectangle – 130 × 180 mm'],
        ['Cutting Speed', '20 – 80 mtr/min'],
        ['Blade Size', '2910 × 27 × 0.9 mm'],
        ['Blade Tension', 'Manual'],
        ['Saw Motor', '2.0 HP'],
        ['Hydraulic Motor', '0.5 HP'],
        ['Coolant Motor', '0.15 HP'],
        ['Job Clamping', 'Hydraulic'],
        ['Hydraulic Reservoir', '25 Ltr'],
        ['Overall Dimension', '1560 × 850 × 1250 mm'],
      ],
    },
    {
      name: 'MEC 250 SCH', badge: 'MILD STEEL', badgeCls: 'bg-emerald-900 text-white',
      subtitle: 'Mild Steel Metal Cutting Bandsaw Machine',
      img: 'https://mectechnology.co.in/wp-content/uploads/2024/08/swing-type-metal-cutting-bandsaw-machine-200-ach-500x500-2.webp',
      desc: 'With expertise in this domain, we manufacture, supply and export High-Speed Metal Cutting Band Saw Machines widely used for job shop applications. Complies with international quality standards.',
      features: [
        'Semi Automatic bandsaw machine',
        'Ergonomic Design',
        'Hydraulic job clamping',
        'Hydraulic cylinder feed control',
        'Auto Saw off & Head up after finishing cut',
        'Machine with easy control & working height 700 mm',
      ],
      specs: [
        ['Cutting Capacity', 'Round – 250 mm, Rectangle – 250 × 250 mm'],
        ['Cutting Speed', '20 – 80 mtr/min'],
        ['Blade Tension', 'Manual'],
        ['Saw Motor', '2.0 HP'],
        ['Hydraulic Motor', '0.5 HP'],
        ['Job Clamping', 'Hydraulic'],
      ],
    },
  ],
};

export default function SwingTypePage({ navigate }) {
  return <ProductPageTemplate pageData={pageData} navigate={navigate} />;
}
